### PR TITLE
fix(meta): add r-base 3.6.3 supported

### PR DESCRIPTION
**Pull request by FernandezMathieu**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by dbast** [comment]
What is the intention of this PR? It still builds for R 4/4.1

**Comment by FernandezMathieu** [comment]
Hi @dbast 
I try to build this package with r-base 3.6.3.
I excepted the same behavior as python when i remove the `noarch` part but that don't work, so i tried to create my own ci files with r-base 3.6.3, but this doesn't work too. 
Maybe i misunderstood something, but the documentation for r packages is very light.
What do i have to put in the `meta.yaml` file to be able to build the package for r-base under version 4 ?

**Comment by dbast** [comment]
Hm... this won't work via changing the meta.yaml (R 3.6 is also out of conda-forge support)... have a look at the files in https://github.com/conda-forge/r-r2dii.match-feedstock/tree/master/.ci_support ... maybe create a conda_build_config.yaml and specify all 3 R versions 3.6, 4.0, 4.1.

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Comment by FernandezMathieu** [comment]
@conda-forge-admin please rerender

**Pull request merged**
